sanergy/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.contrib.auth import views
import sanitation.urls


urlpatterns = [
    url('admin/', admin.site.urls),
    url('',include('sanitation.urls')),
    url('accounts/',include('registration.backends.simple.urls')),
   
]

sanitation/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include
from . import views


urlpatterns = [
    url(r'^$',views.index, name=  "homePage"),
    url(r'^payment', views.payment, name='payment'),
    url(r'^toilet', views.toilet, name='toilet'),
    url('access/token', views.getAccessToken, name='get_mpesa_access_token'),
    url('online/lipa', views.lipa_na_mpesa_online, name='lipa_na_mpesa'),
    #profile
    url(r'^my-profile/',views.my_profile, name='my-profile'),
    url(r'^user/(?P<username>\w{0,50})',views.user_profile,name='user-profile'),
    url(r'^create/profile$',views.create_profile, name='create-profile'),
    url(r'^update/profile$',views.update_profile, name='update-profile'),


]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT) 

sanitation/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser,User

# class User(models.Model):
#     first_name=models.CharField(max_length = 65, blank=True)
#     last_name=models.CharField(max_length = 65, blank=True)
#     phone_number=models.IntegerField(default=0, blank= True)
#     user_id_number= models.IntegerField(default=0, blank=True)
#     location=models.CharField(max_length = 65, blank=True)




class Profile(models.Model):
    username = models.ForeignKey(User,on_delete=models.CASCADE)
    phone_number = models.CharField(default=None,max_length=10)
    id_number =models.CharField(max_length=10,default=None)






class Payment(models.Model):
    name = models.CharField(max_length = 65, blank=True)
    account = models.CharField(max_length = 65, blank=True)
    phone_Number= models.IntegerField(default=0)
    amount = models.IntegerField(default=0)


    def __str__(self):
        return self.name

    def save_payment(self):
        self.save()    


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    class Meta:
        abstract = True
# M-pesa Payment models
class MpesaCalls(BaseModel):
    ip_address = models.TextField()
    caller = models.TextField()
    conversation_id = models.TextField()
    content = models.TextField()
    class Meta:
        verbose_name = 'Mpesa Call'
        verbose_name_plural = 'Mpesa Calls'
class MpesaCallBacks(BaseModel):
    ip_address = models.TextField()
    caller = models.TextField()
    conversation_id = models.TextField()
    content = models.TextField()
    class Meta:
        verbose_name = 'Mpesa Call Back'
        verbose_name_plural = 'Mpesa Call Backs'
class MpesaPayment(BaseModel):
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    type = models.TextField()
    reference = models.TextField()
    first_name = models.CharField(max_length=100)
    middle_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    phone_number = models.TextField()
    organization_balance = models.DecimalField(max_digits=10, decimal_places=2)
    class Meta:
        verbose_name = 'Mpesa Payment'
        verbose_name_plural = 'Mpesa Payments'
    def __str__(self):
        return self.first_name        

class Toilet(models.Model):
    account_number= models.CharField(max_length=100)
    toilet_tag= models.CharField(max_length=100)
    user_id_number = models.ForeignKey(User,on_delete=models.CASCADE,null=True)

    def save_toilet(self):
        self.save()

    def __str__(self):
        return self.toilet    

sanitation/forms.py
from django import forms
from.models import *



class PaymentForm(forms.ModelForm):
    class Meta:
        model  = Payment
        fields = ['name','account','phone_Number','amount']

class ToiletForm(forms.ModelForm):
    class Meta:
        model  = Toilet
        fields = ['account_number','toilet_tag',]

class ProfileForm(forms.ModelForm):
    class Meta:
        model=Profile
        exclude=['username']

sanitation/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse,HttpResponseRedirect
from .models import *
from .forms import *
from django.shortcuts import get_object_or_404
import requests
from requests.auth import HTTPBasicAuth
import json
from .mpesa_credentials import *
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request, 'index.html')


# Create your views here.
@login_required(login_url='/accounts/login/')
def my_profile(request):
    current_user=request.user
    profile =Profile.objects.get(username=current_user)
    return render(request,'profile/user_profile.html',{"profile":profile})

# def redirection(request):
#     if user.is_valid() == True:
#         return render(request,'payment.html')    


# @login_required(login_url='/accounts/login/')
# def user_profile(request,username):
#     user = User.objects.get(username=username)
#     profile =Profile.objects.get(username=user)

@login_required(login_url='/accounts/login/')
def create_profile(request):
    current_user=request.user
    if request.method=="POST":
        form =ProfileForm(request.POST,request.FILES)
        if form.is_valid():
            profile = form.save(commit = False)
            profile.username = current_user
            profile.save()
        return HttpResponseRedirect('/')
    else:
        form = ProfileForm()
        return render(request,'profile/profile_form.html',{"form":form})
    

@login_required(login_url='/accounts/login/')
def update_profile(request):
    current_user=request.user
    if request.method=="POST":
        instance = Profile.objects.get(username=current_user)
        form =ProfileForm(request.POST,request.FILES,instance=instance)
        if form.is_valid():
            profile = form.save(commit = False)
            profile.username = current_user
            profile.save()

        return redirect('index')

    elif Profile.objects.get(username=current_user):
         profile = Profile.objects.get(username=current_user)
         form = ProfileForm(instance=profile)
    else:
        form = ProfileForm()

    return render(request,'profile/update_profile.html',{"form":form})


def payment(request):
    if request.method == 'POST':
        form=PaymentForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            name=form.save(commit=False)
            phone_Number=form.save(commit=False)
            amount=form.save(commit=False)
            account=form.save(commit=False)
            payment.save()
            return redirect(hood)
    else:
        form=PaymentForm()
    return render(request, 'payment.html', locals())

def toilet(request):


    this_user_id_number=User.objects.all()
    if request.method == 'POST':

        form=ToiletForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            account_number=form.save(commit=False)
            toilet_tag=form.save(commit=False)
            # toilet.save()
            return redirect(index)
    else:
        form=ToiletForm()
    return render(request, 'toilet.html', locals())




def getAccessToken(request):
    consumer_key='cHnkwYIgBbrxlgBoneczmIJFXVm0oHky'
    consumer_secret='2nHEyWSD4VjpNh2g'
    api_URL='https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials'
    r=requests.get(api_URL, auth=HTTPBasicAuth(consumer_key, consumer_secret))
    mpesa_access_token=json.loads(r.text)
    validated_mpesa_access_token=mpesa_access_token['access_token']
    return HttpResponse(validated_mpesa_access_token)
def lipa_na_mpesa_online(request):
    access_token=MpesaAccessToken.validated_mpesa_access_token
    api_url="https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest"
    headers={"Authorization": "Bearer %s" % access_token}
    request={
        "BusinessShortCode": LipanaMpesaPpassword.Business_short_code,
        "Password": LipanaMpesaPpassword.decode_password,
        "Timestamp": LipanaMpesaPpassword.lipa_time,
        "TransactionType": "CustomerPayBillOnline",
        "Amount": 1,
        "PartyA": 254717654230,  # replace with your phone number to get stk push
        "PartyB": LipanaMpesaPpassword.Business_short_code,
        "PhoneNumber": 254717654230,  # replace with your phone number to get stk push
        "CallBackURL": "https://sandbox.safaricom.co.ke/mpesa/",
        "AccountReference": "Obindi",
        "TransactionDesc": "Testing stk push"
    }
    response=requests.post(api_url, json=request, headers=headers)
    return HttpResponse('success')

sanitation/templates/base.html
{% load bootstrap3 %}
{% load static %}





<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Sanergy</title>

    {%block styles%}
      {%bootstrap_css%}
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.6/dist/jquery.fancybox.min.css" />
    {%endblock%}

  </head>
  <body> 
    {% block content %}
      {% include "navbar.html" %}
    {% endblock %}

    {% block scripts %}
      {% bootstrap_javascript %}
        <script type="text/javascript" src="{% static 'js/base.js' %}"></script>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.6/dist/jquery.fancybox.min.js"></script>
    {% endblock %}
  </body>
</html>

sanitation/templates/data.html
{% extends 'base.html' %}
{% block content %}
{{ block.super}}
{% load bootstrap3%}

<div class="container">
    <div id="logo">
    
    <a class="logo" href="http://www.sanergy.com">
    <img class="fixed-logo" src="http://www.sanergy.com/wp-content/uploads/2018/11/logo-small-color-195.png" width="160px" alt="Sanergy">
    <img class="nav-logo" src="http://www.sanergy.com/wp-content/uploads/2018/11/logo-small-white-195.png" width="160px" alt="Sanergy">
    </a>
   
      
</div>     
    

sanitation/templates/index.html
{% extends 'base.html' %}
{% block content %}
{{ block.super}}
{% load bootstrap3 %}
{% load static %}
<style>

@import url('https://fonts.googleapis.com/css?family=Work+Sans:400,600');

.container {
	width: 80%;
	margin: 0 auto;
}

header {
  background: none;
}

header::after {
  content: '';
  display: table;
  clear: both;
}

.logo {
  float: left;
  padding: 10px 0;
}

nav {
  float: right;
}

nav ul {
  margin: 0;
  padding: 0;
  list-style: none;
}

nav li {
  display: inline-block;
  margin-left: 70px;
  padding-top: 23px;

  position: relative;
}

nav a {
  color: #eedc12;
  text-decoration: none;
  text-transform: uppercase;
  font-size: 14px;
}

nav a:hover {
  color: white;
  

nav a::before {
  content: '';
  display : block;
  height: 5px;
  background-color: #444;

  position: absolute;
  top: 0;
  width: 0%;

  transition: all ease-in-out 250ms;
}

nav a:hover::before {
  width: 100%;
}

</style>

   
    <div class="slider-parallax-inner"
    style="background: url('static/img/slum.jpg') center center no-repeat; background-size: 100%; height: 700px; background-attachment: fixed;">
    <div class="container">
    <div id="logo">
    
    <a class="logo" href="{% url 'homePage' %}">
    <header>
    <div class="container">
     
    <img class="fixed-logo"  src="http://www.sanergy.com/wp-content/uploads/2018/11/logo-small-color-195.png" width="180px" alt="Sanergy">
   
      <nav>
        <ul>
          <li><a href="{% url 'homePage' %}">Home</a></li>
          <li><a class="nav-link" href="/accounts/register">Sign In</a></li>
          <a class="nav-link" href="{% url 'user-profile' %}">Account</a>
          <!-- <a class="nav-link" href="{% url 'update-profile' %}">Edit Profile</a> -->

          <li><a href="/account/login">Staff Login</a></li>
          
        </ul>
      </nav>
    </div>
  </header>
    </a>
    </div>
        <div>
            <p style="text-align: center; color:white;;font-weight: bold;line-height: 1.4;font-size: 90px;padding-top:200px;">Clean communities,  </p>
            <p style="text-align: center; color:white;font-weight: bold;line-height: 1.4;font-size: 90px;">a cleaner country.</p>
        </div>
    </div>

</div>
<br>
<br>
<h1 style="color: #005486ff;text-align: center;font-family:Montserrat;font-weight:700;font-style:normal ;font-size:40px; " class="vc_custom_heading">THE URBAN SANITATION</h1>

<br>
<br>
<br>

    <div class="vc_row wpb_row vc_inner vc_row-fluid vc_row-o-content-middle vc_row-flex"><div class="wpb_column vc_column_container vc_col-sm-12"><div class="vc_column-inner"><div class="wpb_wrapper">
    <div class="wpb_text_column wpb_content_element ">
    <div class="wpb_wrapper">
    <p dir="ltr" style="text-align: center;"><span style="color: #005486ff; font-size:20px;">Cities are growing faster than ever. Currently, 60 million new residents move to urban areas every year.<br>
25% live in slums, amounting to 1 billion people with inadequate housing and limited access to basic<br>
services. This number is expected to double to 2 billion by 2030.<br>
In Kenya, loss of productivity due to illness costs the country 1% of its GDP every year and at current<br>
rates, complete sanitation coverage will take 150 years. Sanergy provides non-sewered sanitation<br>
solutions that serve all urban residents and are 4 times cheaper than sewers.</span></p>
    </div>
    <br>
    <br>
    <br>
    </div>
    </div></div></div></div>

</div>
<div class="maps"
    style="background: url('static/img/map10.jpg') center center no-repeat; background-size: 100%; height: 300px; background-attachment: fixed; ">
    <div class="loc" style="padding-left: 800px;padding-top: 140px;">
        <i class="glyphicon glyphicon-map-marker " aria-hidden="true"></i> <a target="_blank"
            href="https://www.google.com/maps/search/?api=1&query=laundry_shops" style="color:rgb(14, 13, 13)"
            >
            
        </a></div>
</div>

<button onclick="topFunction()" id="myBtn" title="Go to top"><img src="static/icons/chevron-up.png"></button>

<div id="contacts"
    style="background: url('static/img/map10.jpg') center center no-repeat; background-size: 100%; height: 800px; background-attachment: fixed;">

    <h6 style=" font-family: 'Nunito', sans-serif;
    text-align: center;
    font-size: 90px;
    color: #eedc12;"> Contacts</h6>
    <div class="row">
        <div class="col-lg-4 " styles="text-align: center;color:white;font-size:40px;">
        
            <br><br>
            <div id="call " style="font-size: 20px;
        color:#eedc12;">
                
                
            </div>
        </div>
        <br>
        <br>
        <div class="col-lg-3 quick" style="color: azure;
      font-family: 'Nunito', sans-serif;color:#eedc12;font-size:20px;">
      <br>
      <br>
            <h3 style="font-weight:700;">Reach Us</h3>
            <br>
            <ul>
                <p>Sameer Africa, Enterprise Road</p>
                <p>Nairobi, Kenya</p>
                <p>+254 788 511 824</p>
                <p>info@saner.gy</p>
                <p>Privacy Policy</p>
                
            </ul>
        </div>
        <br>
        <br>
        <div class="col-lg-2 quick" style="color: azure;
    font-family: 'Nunito', sans-serif;font-size:20px;color:#eedc12;">
    <br>
    <br>
            <h3 style="font-weight:700;">Follow Us</h3>
            <br>
            <ul>
                <img src="static/icons/icn_google.png">
                <img src="static/icons/icn_instagram.png">
                <img src="static/icons/icn_linkedin.png">
                <img src="static/icons/icn_twitter.png">
                
            </ul>
        </div>

       
    </div>
    
    <div class="footer">
        <div id="icons" styles="align: center; color:#eedc12;">
            
        </div>
        
        
        </div>
    </div>      
</div>





<script src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

<script>
    $(document).ready(function () {
        var qty = $("#qty");
        qty.keyup(function () {
            var total = isNaN(parseInt(qty.val() * $("#price").val())) ? 0 : (qty.val() * $("#price").val())
            $("#total").val(total);
        });
    });
    $(document).ready(function () {
        var qty1 = $("#qty1");
        qty1.keyup(function () {
            var total1 = isNaN(parseInt(qty1.val() * $("#price1").val())) ? 0 : (qty1.val() * $("#price1").val())
            $("#total1").val(total1);
        });
    });
    $(document).ready(function () {
        var qty2 = $("#qty2");
        qty2.keyup(function () {
            var total2 = isNaN(parseInt(qty2.val() * $("#price2").val())) ? 0 : (qty2.val() * $("#price2").val())
            $("#total2").val(total2);
        });
    });
    $(document).ready(function () {
        var grandTotal = $("#grandTotal");
        ("#btn-sum").onClick(function () {
            var grandTotal = isNaN(parseInt($("#total").val() + $("#total1").val()) + $("#total2").val())
            $("#total2").val(total2);
        });
    });
       // When the user scrolls down 20px from the top of the document, show the button
       window.onscroll = function () { scrollFunction() };
    function scrollFunction() {
        if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {
            document.getElementById("myBtn").style.display = "block";
        } else {
            document.getElementById("myBtn").style.display = "none";
        }
    }
    // When the user clicks on the button, scroll to the top of the document
    function topFunction() {
        document.body.scrollTop = 0;
        document.documentElement.scrollTop = 0;
    }
</script>

<style>
    .jumbotron {
        color: rgba(0, 0, 0, 0.5);
    }
    
    
    h3 {
        text-align: center;
    }
    .pacifico {
        font-family: 'Pacifico', cursive;
    }
    .col-md-4.col-sm-12 {
        text-align: center;
    }
    @media only screen and (max-width: 600px) {
        
        .display-1 {
            font-size: 2.5rem;
        }
    }
    #myBtn {
        display: none;
        position: fixed;
        bottom: 20px;
        right: 30px;
        z-index: 99;
        font-size: 18px;
        border: none;
        outline: none;
        background-color: transparent;
        color: white;
        cursor: pointer;
        padding: 15px;
        border-radius: 4px;
    }
</style>

    
    
    
      {% endblock %}

sanitation/templates/payment.html
{% extends 'base.html' %}
{% block content %}
{{ block.super}}
{% load bootstrap3%}
<style>

#id_name{
    height: 50px;
    border-radius: 25px;
    text-align:center;
    font-size:17px;
    color: #005486ff;
    font-weight:bold;
}
#id_account{
    height: 50px;
    border-radius: 25px;
    text-align:center;
    font-size:17px;
    color: #005486ff;
    font-weight:bold;
}

#id_phone_Number{
    height: 50px;
    border-radius: 25px;
    text-align:center;
    font-size:17px;
    color: #005486ff;
    font-weight:bold;
}
#id_amount{
    height: 50px;
    border-radius: 25px;
    text-align:center;
    font-size:17px;
    color: #005486ff;
    font-weight:bold;
}

</style>
<body style="background: url('static/img/slum.jpg');">
<br>
<br>

<a class="logo" href="{% url 'homePage' %}">

    <div class="container" style="background-color:none;text-align:center; color:#eedc12; font-size:25px">
        <img class="fixed-logo"  src="http://www.sanergy.com/wp-content/uploads/2018/11/logo-small-color-195.png" width="180px" alt="Sanergy">
        <br>
        <br>
        <br>
        <form action="{% url 'payment' %}" method="POST" enctype="multipart/form-data" style="background:none; ">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-primary" value="Update" style="border-radius: 15px 50px 30px; color:#eedc12 ;font-size:25px">
        </form>
    </div>
</body>
{% endblock %}

sanitation/templates/toilet.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{{ block.super}}
{% load bootstrap3%}

<style>

#id_account_number{
    height: 50px;
    border-radius: 25px;
    text-align:center;
    font-size:17px;
    color: #005486ff;
    font-weight:bold;
}
#id_toilet_tag{
    height: 50px;
    border-radius: 25px;
    text-align:center;
    font-size:17px;
    color: #005486ff;
    font-weight:bold;
}
</style>
<body style=" background: url('static/img/slum.jpg');" >
<br>
<br>


    <div class="container"style="background-color:none;text-align:center; color:#eedc12; font-size:20px">
    <br>
  
        <img class="fixed-logo"  src="http://www.sanergy.com/wp-content/uploads/2018/11/logo-small-color-195.png" width="180px" alt="Sanergy">
        <br>
        <br>
        <br>
        <br>

        
        <br>
  
            
            <form action="{% url 'toilet' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {% bootstrap_form form %}
                <br>
                
                <input type="submit" class="btn btn-primary" value="Register" style="border-radius: 15px 50px 30px; color:#eedc12 ;font-size:20px">
            </form>
        
    </div>
</body>
{% endblock %}